version: "3.8"

services:

  migration:
    command: "npm run -w database migrations:up"
    depends_on:
      - dynamodb
    build:
      context: ../
      dockerfile: ./docker/database.Dockerfile
    environment: 
      DYNAMODB_HOST: http://dynamodb
      DYNAMODB_PORT: ${DYNAMODB_PORT}
  
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "${DYNAMODB_PORT}:8000"
    # ubuntu volume permission issue
    # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volumes-lack-permission-unable-to-open-databa
    # volumes:
      # - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal