version: "3.8"

services:
  
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    ports:
      - "${DYNAMODB_PORT}:8000"
    # ubuntu volume permission issue
    # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volumes-lack-permission-unable-to-open-databa
    # volumes:
      # - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal