name: Build and Test

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Setup local DynamoDB
        run: docker run -p 8000:8000 amazon/dynamodb-local -jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./ &
      - run: npm ci
      - run: npm test
        env:
          DYNAMODB_HOST: "http://127.0.0.1"
          DYNAMODB_PORT: "8000"
